on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          build_command: npm run build
          path: storybook-static
        # Bump the version & push (if you're not doing that elsewhere)
      - name: Bump version & push
        run: |
          git config --global user.name 'Automated publish'
          git config --global user.email 'webdevtrev@users.noreply.github.com'
          npm version patch
          git push && git push --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
